name: dva
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip

  # Core scientific stack
  - numpy
  - pandas
  - matplotlib

  # Geo stack
  - geopandas
  - shapely
  - pyogrio

  # App + viz
  - streamlit
  - pydeck
  - plotly

  # Model explainability
  - shap
